# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type',models.IntegerField(choices=[(1, 'Moda'), (2, 'Culture'), (3, 'Glamur')], default=0)),
                ('content',ckeditor.fields.RichTextField(default='')),
                ('cover',models.ImageField(blank=True, null=True, upload_to='blog/media/'), )
            ],
        ),
    ]
