# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, 'Moda'), (2, 'Culture')], default=0),
        ),
    ]
