# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:16
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, 'Moda'), (2, 'Culture'), (3, 'Glamur')], default=0),
        ),
    ]
